Repository openshift/etcd, pull requests merged in 2019-02, with the labels that each got.

#4 Dockerfile: add etcdctl
  Dockerfile.openshift
  Dockerfile.rhel
Labels: approved, size/XS

#2 Dockerfile.*: Fix "etcd is distributed" -> "etcd is a distributed"
  Dockerfile.openshift
  Dockerfile.rhel
Labels: lgtm, size/XS

#5 Dockerfile: resolve issue where binary was not properly copied
  Dockerfile.openshift
  Dockerfile.rhel
Labels: approved, lgtm, size/XS
