Repository openshift/etcd, pull requests merged in 2020-02, with the labels that each got.

#26 add stub discovery-etcd-initial-cluster
  Dockerfile.openshift
  Dockerfile.rhel
  build
  openshift-tools/discover-etcd-initial-cluster/main.go
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, lgtm, size/L

#28 bug 1805807: create logic for golang ETCD_INITIAL_CLUSTER
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#27 bug 1805809: create logic for golang ETCD_INITIAL_CLUSTER
  Dockerfile.openshift
  Dockerfile.rhel
  build
  openshift-tools/discover-etcd-initial-cluster/main.go
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#30 Use var lib etcd as data dir
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, lgtm, size/S

#29 Bug 1806751: Archive data-dir if target member is unstarted
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#32 Bug 1806752: [release 4.4] Archive data dir if unstarted 4.4
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#34 Bug 1808073: fix archive member name, unmask error
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, lgtm, size/XS

#36 Bug 1808544: If we weren't able to get client or target member go ahead and start ...
  openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
