Repository openshift/etcd, pull requests merged in 2025-02, with the labels that each got.

#308 ETCD-709: Rebase etcd 3.5.18 openshift 4.19
  .go-version
  api/go.mod
  api/go.sum
  api/version/version.go
  client/pkg/go.mod
  client/pkg/go.sum
  client/v2/go.mod
  client/v3/go.mod
  client/v3/go.sum
  client/v3/lease.go
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/ctl.go
  etcdutl/etcdutl/check_command.go
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  scripts/release_notes.tpl.txt
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  server/etcdserver/server.go
  server/go.mod
  server/go.sum
  server/mvcc/key_index.go
  server/mvcc/key_index_test.go
  server/mvcc/kv_test.go
  server/mvcc/kvstore.go
  tests/e2e/etcd_config_test.go
  tests/e2e/etcd_mix_versions_test.go
  tests/e2e/v2store_deprecation_test.go
  tests/e2e/watch_test.go
  tests/go.mod
  tests/go.sum
  tests/integration/clientv3/lease/lease_test.go
  tests/integration/embed/embed_test.go
  tools/mod/go.mod
  tools/mod/go.sum
Labels: lgtm, approved, jira/valid-reference

#307 ETCD-708: Rebase etcd 3.5.18 openshift 4.18
  .go-version
  api/go.mod
  api/go.sum
  api/version/version.go
  client/pkg/go.mod
  client/pkg/go.sum
  client/v2/go.mod
  client/v3/go.mod
  client/v3/go.sum
  client/v3/lease.go
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/ctl.go
  etcdutl/etcdutl/check_command.go
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  scripts/release_notes.tpl.txt
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdmain/config.go
  server/etcdmain/help.go
  server/etcdserver/server.go
  server/go.mod
  server/go.sum
  server/mvcc/key_index.go
  server/mvcc/key_index_test.go
  server/mvcc/kv_test.go
  server/mvcc/kvstore.go
  tests/e2e/etcd_config_test.go
  tests/e2e/etcd_mix_versions_test.go
  tests/e2e/v2store_deprecation_test.go
  tests/e2e/watch_test.go
  tests/go.mod
  tests/go.sum
  tests/integration/clientv3/lease/lease_test.go
  tests/integration/embed/embed_test.go
  tools/mod/go.mod
  tools/mod/go.sum
Labels: lgtm, approved, staff-eng-approved, jira/valid-bug, jira/valid-reference

#309 DOWNSTREAM: <carry>: OCPBUGS-51838: fix a compaction induce latency issue
  server/mvcc/kvstore_compaction.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
