Repository openshift/etcd, pull requests merged in 2025-03, with the labels that each got.

#315 ETCD-717: Rebase etcd 3.5.19 openshift 4.19
  .ci-operator.yaml
  .github/workflows/release.yaml
  .github/workflows/verify-released-assets.yaml
  .go-version
  Dockerfile.art
  Dockerfile.art-cachi2
  Dockerfile.installer
  Dockerfile.installer.art
  Dockerfile.installer.art-cachi2
  Dockerfile.rhel
  api/go.mod
  api/go.sum
  api/version/version.go
  client/pkg/go.mod
  client/pkg/go.sum
  client/v2/go.mod
  client/v3/go.mod
  client/v3/go.sum
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  server/etcdserver/api/etcdhttp/health.go
  server/etcdserver/api/etcdhttp/health_test.go
  server/etcdserver/api/membership/cluster.go
  server/go.mod
  server/go.sum
  tests/go.mod
  tests/go.sum
  tools/benchmark/cmd/txn_mixed.go
  tools/mod/go.mod
  tools/mod/go.sum
Labels: lgtm, approved, staff-eng-approved, jira/valid-bug, jira/valid-reference

#312 DOWNSTREAM: <carry>: OCPBUGS-51971: fix a compaction induce latency issue
  server/mvcc/kvstore_compaction.go
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#311 OCPBUGS-50510: Add configurable option for hardware-related timeout delay
  server/config/config.go
  server/wal/wal.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#310 ETCD-714: Rebase etcd 3.5.18 openshift 4.17
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .go-version
  api/go.mod
  api/go.sum
  api/version/version.go
  client/pkg/go.mod
  client/pkg/go.sum
  client/v2/go.mod
  client/v3/README.md
  client/v3/go.mod
  client/v3/go.sum
  client/v3/lease.go
  etcdctl/go.mod
  etcdctl/go.sum
  etcdutl/ctl.go
  etcdutl/etcdutl/check_command.go
  etcdutl/go.mod
  etcdutl/go.sum
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
  raft/go.mod
  scripts/release.sh
  scripts/release_notes.tpl.txt
  server/embed/etcd.go
  server/embed/serve.go
  server/etcdmain/config.go
  server/etcdmain/grpc_proxy.go
  server/etcdmain/help.go
  server/etcdserver/api/v3rpc/watch.go
  server/etcdserver/apply.go
  server/etcdserver/apply_test.go
  server/etcdserver/server.go
  server/go.mod
  server/go.sum
  server/mvcc/backend/backend.go
  server/mvcc/key_index.go
  server/mvcc/key_index_test.go
  server/mvcc/kv_test.go
  server/mvcc/kvstore.go
  tests/e2e/defrag_no_space_test.go
  tests/e2e/etcd_config_test.go
  tests/e2e/etcd_grpcproxy_test.go
  tests/e2e/etcd_mix_versions_test.go
  tests/e2e/logging_test.go
  tests/e2e/v2store_deprecation_test.go
  tests/e2e/watch_test.go
  tests/go.mod
  tests/go.sum
  tests/integration/clientv3/lease/lease_test.go
  tests/integration/embed/embed_test.go
  tools/mod/go.mod
  tools/mod/go.sum
Labels: lgtm, approved, cherry-pick-approved, staff-eng-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#313 OCPBUGS-52181: Ensure cluster id changes during force-new-cluster
  server/etcdserver/api/rafthttp/pipeline.go
  server/etcdserver/raft.go
  server/wal/wal.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
